name: Student App API tests run newman from docker container

on: 
  push:
      branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Node
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'

    - name: Install Newman
      run: npm i
            
    - name: Make directory for results
      run: mkdir -p newman

    - name: Run API Tests
      run: npm test

    - name: Output test results
      uses: actions/upload-artifact@v3
      with:
        name: RunReports
        path: newman
    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v3
    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: newman